bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'nulo'
keystore_file = 'agente_null.key'
name = 'carlos'
public_address = 'HcScjnZOKDU9vbycti8dpvG9mjirgxcuswwkrjOGguqrf6ohD8CzPuJdBdqrndz'

[[dnas]]
file = '/home/empleado/Escritorio/holo_wiki/dist/holo_wiki.dna.json'
hash = 'QmWpPdpPihWzwyyy2hvG885VSPRxWbJSm3PfwQCzjQAbFe'
id = 'hc-run-dna'

[[instances]]
agent = 'nulo'
dna = 'hc-run-dna'
id = '__H_Wiki2'

[instances.storage]
type = 'memory'


[[interfaces]]
admin = false
id = 'websocket-interface2'

[[interfaces.instances]]
id = '__H_Wiki2'

[interfaces.driver]
port = 3402
type = 'http'

[logger]
state_dump = false
type = 'debug'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
[network]
type="sim2h"
sim2h_url="ws://0.0.0.0:9000"
